platform :ios, "9.0"

target "车无忧" do
pod 'SDCycleScrollView','~> 1.66'
pod 'AFNetworking', '~> 3.1.0'
pod "PYSearch"
pod 'MBProgressHUD', '~> 1.0.0'
pod 'MJRefresh'
pod 'MJExtension'
pod 'Masonry'
pod 'SVProgressHUD'
pod 'BaiduMapKit'
pod 'YYModel'
pod 'CYLTableViewPlaceHolder'
pod 'NJKWebViewProgress'
end